# Generated by Django 4.2.1 on 2023-07-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0030_remove_course_content_alter_course_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizresult",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quizresult",
            name="student",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="quiz",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
        migrations.DeleteModel(
            name="QuizResult",
        ),
    ]
